In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
df = pd.read_csv('House_Price.csv')
df

price  resid_area  air_qual  room_num   age  dist1  dist2  dist3  dist4  \
0     24.0       32.31     0.538     6.575  65.2   4.35   3.81   4.18   4.01   
1     21.6       37.07     0.469     6.421  78.9   4.99   4.70   5.12   5.06   
2     34.7       37.07     0.469     7.185  61.1   5.03   4.86   5.01   4.97   
3     33.4       32.18     0.458     6.998  45.8   6.21   5.93   6.16   5.96   
4     36.2       32.18     0.458     7.147  54.2   6.16   5.86   6.37   5.86   
..     ...         ...       ...       ...   ...    ...    ...    ...    ...   
501   22.4       41.93     0.573     6.593  69.1   2.64   2.45   2.76   2.06   
502   20.6       41.93     0.573     6.120  76.7   2.44   2.11   2.46   2.14   
503   23.9       41.93     0.573     6.976  91.0   2.34   2.06   2.29   1.98   
504   22.0       41.93     0.573     6.794  89.3   2.54   2.31   2.40   2.31   
505   19.0       41.93     0.573     6.030  80.8   2.72   2.24   2.64   2.42   

     teachers  poor_prop airport  n_hos_beds  n_hot_rooms       waterbody  \
0        24.7       4.98     YES       5.480      11.1920           River   
1        22.2       9.14      NO       7.332      12.1728            Lake   
2        22.2       4.03      NO       7.394     101.1200             NaN   
3        21.3       2.94     YES       9.268      11.2672            Lake   
4        21.3       5.33      NO       8.824      11.2896            Lake   
..        ...        ...     ...         ...          ...             ...   
501      19.0       9.67      NO       9.348      12.1792  Lake and River   
502      19.0       9.08     YES       6.612      13.1648  Lake and River   
503      19.0       5.64      NO       5.478      12.1912             NaN   
504      19.0       6.48     YES       7.940      15.1760             NaN   
505      19.0       7.88     YES      10.280      10.1520             NaN   

     rainfall bus_ter     parks  Sold  
0          23     YES  0.049347     0  
1          42     YES  0.046146     1  
2          38     YES  0.045764     0  
3          45     YES  0.047151     0  
4          55     YES  0.039474     0  
..        ...     ...       ...   ...  
501        27     YES  0.056006     1  
502        20     YES  0.059903     1  
503        31     YES  0.057572     1  
504        47     YES  0.060694     1  
505        45     YES  0.060336     1  

[506 rows x 19 columns]

In [3]:
df.columns

Index(['price', 'resid_area', 'air_qual', 'room_num', 'age', 'dist1', 'dist2',
       'dist3', 'dist4', 'teachers', 'poor_prop', 'airport', 'n_hos_beds',
       'n_hot_rooms', 'waterbody', 'rainfall', 'bus_ter', 'parks', 'Sold'],
      dtype='object')

In [4]:
x = df.drop('Sold', axis=1)
y = df['Sold']


In [5]:
x

price  resid_area  air_qual  room_num   age  dist1  dist2  dist3  dist4  \
0     24.0       32.31     0.538     6.575  65.2   4.35   3.81   4.18   4.01   
1     21.6       37.07     0.469     6.421  78.9   4.99   4.70   5.12   5.06   
2     34.7       37.07     0.469     7.185  61.1   5.03   4.86   5.01   4.97   
3     33.4       32.18     0.458     6.998  45.8   6.21   5.93   6.16   5.96   
4     36.2       32.18     0.458     7.147  54.2   6.16   5.86   6.37   5.86   
..     ...         ...       ...       ...   ...    ...    ...    ...    ...   
501   22.4       41.93     0.573     6.593  69.1   2.64   2.45   2.76   2.06   
502   20.6       41.93     0.573     6.120  76.7   2.44   2.11   2.46   2.14   
503   23.9       41.93     0.573     6.976  91.0   2.34   2.06   2.29   1.98   
504   22.0       41.93     0.573     6.794  89.3   2.54   2.31   2.40   2.31   
505   19.0       41.93     0.573     6.030  80.8   2.72   2.24   2.64   2.42   

     teachers  poor_prop airport  n_hos_beds  n_hot_rooms       waterbody  \
0        24.7       4.98     YES       5.480      11.1920           River   
1        22.2       9.14      NO       7.332      12.1728            Lake   
2        22.2       4.03      NO       7.394     101.1200             NaN   
3        21.3       2.94     YES       9.268      11.2672            Lake   
4        21.3       5.33      NO       8.824      11.2896            Lake   
..        ...        ...     ...         ...          ...             ...   
501      19.0       9.67      NO       9.348      12.1792  Lake and River   
502      19.0       9.08     YES       6.612      13.1648  Lake and River   
503      19.0       5.64      NO       5.478      12.1912             NaN   
504      19.0       6.48     YES       7.940      15.1760             NaN   
505      19.0       7.88     YES      10.280      10.1520             NaN   

     rainfall bus_ter     parks  
0          23     YES  0.049347  
1          42     YES  0.046146  
2          38     YES  0.045764  
3          45     YES  0.047151  
4          55     YES  0.039474  
..        ...     ...       ...  
501        27     YES  0.056006  
502        20     YES  0.059903  
503        31     YES  0.057572  
504        47     YES  0.060694  
505        45     YES  0.060336  

[506 rows x 18 columns]

In [6]:
y

0      0
1      1
2      0
3      0
4      0
      ..
501    1
502    1
503    1
504    1
505    1
Name: Sold, Length: 506, dtype: int64

In [7]:
y.isnull().sum()

0

In [8]:
x.isnull().sum()

price            0
resid_area       0
air_qual         0
room_num         0
age              0
dist1            0
dist2            0
dist3            0
dist4            0
teachers         0
poor_prop        0
airport          0
n_hos_beds       8
n_hot_rooms      0
waterbody      155
rainfall         0
bus_ter          0
parks            0
dtype: int64

In [9]:
# check is there any missing value in the dataset
df.isnull().sum()

price            0
resid_area       0
air_qual         0
room_num         0
age              0
dist1            0
dist2            0
dist3            0
dist4            0
teachers         0
poor_prop        0
airport          0
n_hos_beds       8
n_hot_rooms      0
waterbody      155
rainfall         0
bus_ter          0
parks            0
Sold             0
dtype: int64

In [10]:
x.size

9108

In [11]:
x.shape

(506, 18)

In [12]:
x.columns

Index(['price', 'resid_area', 'air_qual', 'room_num', 'age', 'dist1', 'dist2',
       'dist3', 'dist4', 'teachers', 'poor_prop', 'airport', 'n_hos_beds',
       'n_hot_rooms', 'waterbody', 'rainfall', 'bus_ter', 'parks'],
      dtype='object')

In [13]:
"""
Index(['price', 'resid_area', 'air_qual', 'room_num', 'age', 'dist1', 'dist2',
       'dist3', 'dist4', 'teachers', 'poor_prop', 'airport', 'n_hos_beds',
       'n_hot_rooms', 'waterbody', 'rainfall', 'bus_ter', 'parks'],
      dtype='object')
"""

"\nIndex(['price', 'resid_area', 'air_qual', 'room_num', 'age', 'dist1', 'dist2',\n       'dist3', 'dist4', 'teachers', 'poor_prop', 'airport', 'n_hos_beds',\n       'n_hot_rooms', 'waterbody', 'rainfall', 'bus_ter', 'parks'],\n      dtype='object')\n"

In [14]:
x["waterbody"]

0               River
1                Lake
2                 NaN
3                Lake
4                Lake
            ...      
501    Lake and River
502    Lake and River
503               NaN
504               NaN
505               NaN
Name: waterbody, Length: 506, dtype: object

In [15]:
x["waterbody"].value_counts()

waterbody
River             183
Lake               97
Lake and River     71
Name: count, dtype: int64

In [16]:
# drop the waterbody column
x = x.drop('waterbody', axis=1)

In [17]:
x

price  resid_area  air_qual  room_num   age  dist1  dist2  dist3  dist4  \
0     24.0       32.31     0.538     6.575  65.2   4.35   3.81   4.18   4.01   
1     21.6       37.07     0.469     6.421  78.9   4.99   4.70   5.12   5.06   
2     34.7       37.07     0.469     7.185  61.1   5.03   4.86   5.01   4.97   
3     33.4       32.18     0.458     6.998  45.8   6.21   5.93   6.16   5.96   
4     36.2       32.18     0.458     7.147  54.2   6.16   5.86   6.37   5.86   
..     ...         ...       ...       ...   ...    ...    ...    ...    ...   
501   22.4       41.93     0.573     6.593  69.1   2.64   2.45   2.76   2.06   
502   20.6       41.93     0.573     6.120  76.7   2.44   2.11   2.46   2.14   
503   23.9       41.93     0.573     6.976  91.0   2.34   2.06   2.29   1.98   
504   22.0       41.93     0.573     6.794  89.3   2.54   2.31   2.40   2.31   
505   19.0       41.93     0.573     6.030  80.8   2.72   2.24   2.64   2.42   

     teachers  poor_prop airport  n_hos_beds  n_hot_rooms  rainfall bus_ter  \
0        24.7       4.98     YES       5.480      11.1920        23     YES   
1        22.2       9.14      NO       7.332      12.1728        42     YES   
2        22.2       4.03      NO       7.394     101.1200        38     YES   
3        21.3       2.94     YES       9.268      11.2672        45     YES   
4        21.3       5.33      NO       8.824      11.2896        55     YES   
..        ...        ...     ...         ...          ...       ...     ...   
501      19.0       9.67      NO       9.348      12.1792        27     YES   
502      19.0       9.08     YES       6.612      13.1648        20     YES   
503      19.0       5.64      NO       5.478      12.1912        31     YES   
504      19.0       6.48     YES       7.940      15.1760        47     YES   
505      19.0       7.88     YES      10.280      10.1520        45     YES   

        parks  
0    0.049347  
1    0.046146  
2    0.045764  
3    0.047151  
4    0.039474  
..        ...  
501  0.056006  
502  0.059903  
503  0.057572  
504  0.060694  
505  0.060336  

[506 rows x 17 columns]

In [18]:
x.dtypes

price          float64
resid_area     float64
air_qual       float64
room_num       float64
age            float64
dist1          float64
dist2          float64
dist3          float64
dist4          float64
teachers       float64
poor_prop      float64
airport         object
n_hos_beds     float64
n_hot_rooms    float64
rainfall         int64
bus_ter         object
parks          float64
dtype: object

In [19]:
x["airport"].value_counts()

airport
YES    279
NO     227
Name: count, dtype: int64

In [20]:
# replace the yes and no with 1 and 0
x["airport"] = x["airport"].map({'YES':1, 'NO':0})


In [21]:
x["bus_ter"].value_counts()

bus_ter
YES    506
Name: count, dtype: int64

In [22]:
x["bus_ter"] = x["bus_ter"].map({'YES':1, 'NO':0})

In [23]:
x.dtypes

price          float64
resid_area     float64
air_qual       float64
room_num       float64
age            float64
dist1          float64
dist2          float64
dist3          float64
dist4          float64
teachers       float64
poor_prop      float64
airport          int64
n_hos_beds     float64
n_hot_rooms    float64
rainfall         int64
bus_ter          int64
parks          float64
dtype: object

In [24]:
# check for the missing values
x.isnull().sum()

price          0
resid_area     0
air_qual       0
room_num       0
age            0
dist1          0
dist2          0
dist3          0
dist4          0
teachers       0
poor_prop      0
airport        0
n_hos_beds     8
n_hot_rooms    0
rainfall       0
bus_ter        0
parks          0
dtype: int64

In [25]:
# check for nan values
x.isna().sum()

price          0
resid_area     0
air_qual       0
room_num       0
age            0
dist1          0
dist2          0
dist3          0
dist4          0
teachers       0
poor_prop      0
airport        0
n_hos_beds     8
n_hot_rooms    0
rainfall       0
bus_ter        0
parks          0
dtype: int64

In [26]:
# fill the missing values with the mean of the column
x["n_hos_beds"].fillna(x["n_hos_beds"].mean(), inplace=True)


In [27]:
# import preprocessing from sklearn
from sklearn import preprocessing
# normalize the data
scaler = preprocessing.StandardScaler()

scaler.fit(x)

x = scaler.transform(x)

x

array([[ 0.16037616, -1.2879095 , -0.14421743, ..., -1.29440816,
         0.        , -0.48076306],
       [-0.10125846, -0.59338101, -0.74026221, ...,  0.22543063,
         0.        , -0.78218286],
       [ 1.32683049, -0.59338101, -0.74026221, ..., -0.09453543,
         0.        , -0.81811469],
       ...,
       [ 0.14947472,  0.11573841,  0.15812412, ..., -0.65447604,
         0.        ,  0.29357329],
       [-0.05765269,  0.11573841,  0.15812412, ...,  0.62538821,
         0.        ,  0.58749353],
       [-0.38469596,  0.11573841,  0.15812412, ...,  0.46540518,
         0.        ,  0.55375216]])

In [28]:
# split the data into train and test
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)


In [29]:
# import the logistic regression
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(x_train, y_train)

y_pred = model.predict(x_test)

y_pred

array([1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1], dtype=int64)

In [30]:
# training accuracy
model.score(x_train, y_train)

0.6584158415841584

In [31]:
# check the accuracy of the model
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

0.6764705882352942

In [32]:
# check the confusion matrix
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)



array([[35, 23],
       [10, 34]], dtype=int64)

In [33]:
x_train

array([[ 0.4547151 , -0.72032214, -0.41200566, ..., -1.29440816,
         0.        , -0.08600769],
       [-0.09035701, -0.04768006, -1.22400869, ...,  0.5453967 ,
         0.        , -1.36213903],
       [ 0.48741943, -0.90562701, -1.09443374, ..., -1.21441665,
         0.        , -1.48866948],
       ...,
       [-0.36289307, -0.16440754, -0.06647246, ..., -0.89445058,
         0.        ,  0.59826319],
       [-0.64633057, -0.61672651, -0.92166714, ...,  0.38541367,
         0.        , -0.177735  ],
       [ 0.06226318, -1.03402724, -0.38609067, ..., -0.09453543,
         0.        , -0.14163606]])

In [34]:
# ANN
import tensorflow as tf

model = tf.keras.models.Sequential()

model.add(tf.keras.layers.Dense(units=128, activation='relu', input_shape=(17,)))
model.add(tf.keras.layers.Dense(units=128, activation='relu'))
model.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 128)               2304      
                                                                 
 dense_1 (Dense)             (None, 128)               16512     
                                                                 
 dense_2 (Dense)             (None, 1)                 129       
                                                                 
Total params: 18945 (74.00 KB)
Trainable params: 18945 (74.00 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [35]:
x_train = np.asarray(x_train)
y_train = np.asarray(y_train)

x_train 

array([[ 0.4547151 , -0.72032214, -0.41200566, ..., -1.29440816,
         0.        , -0.08600769],
       [-0.09035701, -0.04768006, -1.22400869, ...,  0.5453967 ,
         0.        , -1.36213903],
       [ 0.48741943, -0.90562701, -1.09443374, ..., -1.21441665,
         0.        , -1.48866948],
       ...,
       [-0.36289307, -0.16440754, -0.06647246, ..., -0.89445058,
         0.        ,  0.59826319],
       [-0.64633057, -0.61672651, -0.92166714, ...,  0.38541367,
         0.        , -0.177735  ],
       [ 0.06226318, -1.03402724, -0.38609067, ..., -0.09453543,
         0.        , -0.14163606]])

In [36]:
model.fit(x_train, y_train, epochs=10)



Epoch 1/10
13/13 [==============================] - 2s 4ms/step - loss: 0.6915 - accuracy: 0.5124
Epoch 2/10
13/13 [==============================] - 0s 2ms/step - loss: 0.6394 - accuracy: 0.6361
Epoch 3/10
13/13 [==============================] - 0s 2ms/step - loss: 0.6246 - accuracy: 0.6634
Epoch 4/10
13/13 [==============================] - 0s 2ms/step - loss: 0.5998 - accuracy: 0.6931
Epoch 5/10
13/13 [==============================] - 0s 2ms/step - loss: 0.5780 - accuracy: 0.7079
Epoch 6/10
13/13 [==============================] - 0s 2ms/step - loss: 0.5579 - accuracy: 0.7030
Epoch 7/10
13/13 [==============================] - 0s 2ms/step - loss: 0.5438 - accuracy: 0.7153
Epoch 8/10
13/13 [==============================] - 0s 2ms/step - loss: 0.5287 - accuracy: 0.7351
Epoch 9/10
13/13 [==============================] - 0s 3ms/step - loss: 0.5190 - accuracy: 0.7302
Epoch 10/10
13/13 [==============================] - 0s 2ms/step - loss: 0.5029 - accuracy: 0.7525


In [37]:
x_test = np.asarray(x_test)
y_test = np.asarray(y_test)

model.evaluate(x_test, y_test)


4/4 [==============================] - 0s 7ms/step - loss: 0.5953 - accuracy: 0.6471


[0.5952875018119812, 0.6470588445663452]

In [40]:
# predict the test data
y_pred = model.predict(x_test)

y_pred
# convert the y_pred to 0 and 1
y_pred = (y_pred > 0.5)

y_pred

4/4 [==============================] - 0s 2ms/step


array([[ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [

In [39]:
y_test

array([1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0], dtype=int64)

In [41]:
# check the accuracy
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)


0.6470588235294118